title: "Dev.Chan64's Blog"
description: "IoT Tech Generalist"
theme: minima

url: "https://devchan64.github.io"
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM   # GitHub Flavored Markdown
  hard_wrap: true
  syntax_highlighter: rouge

paginate: 5
paginate_path: "/blog/page:num/"

defaults:
  - scope:
      path: "_posts/*"
    values:
      layout: "default"