title: "Dev.Chan64's Blog"
description: "Tech Generalist and IoT System Architect with expertise in product execution and cross-domain system integration."
theme: minima

url: "https://devchan64.github.io"
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM   # GitHub Flavored Markdown
  hard_wrap: true
  syntax_highlighter: rouge

paginate: 5
paginate_path: "/blog/page:num/"

defaults:
  - scope:
      path: "_posts/*"
    values:
      layout: "default"

linkedin: "http://www.linkedin.com/in/changbo-sim-bb8397270"