title: "Dev.Chan64's Blog"
description: "Tech Generalist and IoT System Architect with expertise in product execution and cross-domain system integration."
theme: minima
future: true

url: "https://devchan64.github.io"
baseurl: ""
markdown: kramdown
kramdown:
  input: GFM   # GitHub Flavored Markdown
  hard_wrap: true
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  
defaults:
  - scope:
      path: "_posts/*"
    values:
      layout: "post"
  - scope:
      path: "pages/*"
    values:
      layout: "default"

github_profile: "https://github.com/devchan64"
linkedin_profile: "https://www.linkedin.com/in/changbo-sim-bb8397270"

include:
  - README.md
  - en/README.md

exclude:
  - marp
  - vendor
  - "*.sh"
  - Gemfile
  - Gemfile.lock
  - supabase
