name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'supabase/**'
      - 'README.md'
      - '*.sh'
      - '*.py'
      - "_drafts/**"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 빌드
        run: echo "정적 사이트 빌드 작업 수행"
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './' # HTML, CSS, MD 등 배포할 정적 파일 위치
      - uses: actions/deploy-pages@v4
