name: "Hashnode Publish"

on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish to Hashnode
        uses: raunakgurud09/hashnode-publish@v2
        with:
          host: "devchan64.hashnode.dev"
          file: "test/test.md"
          hashnode_key: ${{ secrets.HASHNODE_ACCESS_TOKEN }}
