name: Translate Markdown Posts

on:
  push:
    branches: ["main"]
    paths:
      - '_posts/*.md'
  workflow_dispatch:  # 수동 실행도 가능

permissions:
  contents: write

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai pyyaml --upgrade

      - name: Translate modified posts
        env:
          OPENAPIKEY: ${{ secrets.OPENAPIKEY }}
        run: python translate.py

      - name: Commit translated posts
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add _posts/en
          git commit -m "Auto-translate updated posts to English" || echo "No changes to commit"
          git pull --rebase --autostash
          git push
