name: Translate Markdown Posts

on:
  push:
    paths:
      - '_posts/*.md'
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai

      - name: Translate modified posts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAIAPIKEY }}
        run: python translate.py

      - name: Commit translated posts
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add _posts/en
          git commit -m "Auto-translate updated posts to English" || echo "No changes to commit"
          git push
